sudo: required
sevices:
  - docker

before_install:
  - docker build -t wissallaassilia/react-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true wissallaassilia/react-test npm test

after_success:
  - docker build -t wissallaassilia/multi-client ./client
  - docker build -t wissallaassilia/multi-nginx ./nginx
  - docker build -t wissallaassilia/multi-server ./server
  - docker build -t wissallaassilia/multi-worker ./worker

#Loging to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# take to these images and push them into docker hub

  - docker push wissallaassilia/multi-client 
  - docker push wissallaassilia/multi-nginx
  - docker push wissallaassilia/multi-server
  - docker push wissallaassilia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-141169738969'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



